name: JsDelivrCDNPurge

on:
  push

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/imananoosheh/github-contributions-fetch/generateCalendarScript.js
            https://cdn.jsdelivr.net/gh/imananoosheh/github-contributions-fetch@main/generateCalendarScript.js
            https://cdn.jsdelivr.net/gh/imananoosheh/github-contributions-fetch@latest/generateCalendarScript.js
